# Generated by Django 4.2 on 2025-09-10 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_Course', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('completion', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Learners',
            fields=[
                ('id_learners', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('full_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson_Group',
            fields=[
                ('id_group', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lesson_Group', to='CapyStarAPI.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id_lessons', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('completion', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('Lesson_Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='CapyStarAPI.lesson_group')),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id_level', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Level_name', models.CharField(max_length=255)),
                ('Level_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id_Topic', models.BigAutoField(primary_key=True, serialize=False)),
                ('Topic_name', models.CharField(max_length=100)),
                ('Topic_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id_question', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('question_type', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('reading', 'Reading'), ('grammar', 'Grammar'), ('listening', 'Listening')], max_length=50)),
                ('option_a', models.CharField(blank=True, max_length=200, null=True)),
                ('option_b', models.CharField(blank=True, max_length=200, null=True)),
                ('option_c', models.CharField(blank=True, max_length=200, null=True)),
                ('option_d', models.CharField(blank=True, max_length=200, null=True)),
                ('correct_answer', models.CharField(blank=True, max_length=200, null=True)),
                ('passage', models.TextField(blank=True, null=True)),
                ('grammar_rule', models.TextField(blank=True, null=True)),
                ('grammar_example', models.TextField(blank=True, null=True)),
                ('audio_text', models.CharField(blank=True, max_length=255, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('explain_question', models.TextField(blank=True, null=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='CapyStarAPI.levels')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='CapyStarAPI.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Question_Group',
            fields=[
                ('id_QuestionGroup', models.BigAutoField(primary_key=True, serialize=False)),
                ('Lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question_Group', to='CapyStarAPI.lessons')),
                ('Question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question_Group', to='CapyStarAPI.questionbank')),
                ('Topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Question_Group', to='CapyStarAPI.topic')),
            ],
        ),
        migrations.AddField(
            model_name='lessons',
            name='Level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='CapyStarAPI.levels'),
        ),
        migrations.AddField(
            model_name='lessons',
            name='Topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='CapyStarAPI.topic'),
        ),
        migrations.AddField(
            model_name='lesson_group',
            name='Level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lesson_Group', to='CapyStarAPI.levels'),
        ),
        migrations.AddField(
            model_name='lesson_group',
            name='Topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lesson_Group', to='CapyStarAPI.topic'),
        ),
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id_session', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('time_spent', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='CapyStarAPI.learners')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='CapyStarAPI.lessons')),
            ],
        ),
        migrations.CreateModel(
            name='Learner_Profiles',
            fields=[
                ('id_Profiles', models.BigAutoField(primary_key=True, serialize=False)),
                ('aim', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.DecimalField(blank=0, decimal_places=2, max_digits=4, null=True)),
                ('progress_learners', models.CharField(blank=True, max_length=255, null=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='CapyStarAPI.course')),
                ('Learners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='CapyStarAPI.learners')),
                ('Level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='CapyStarAPI.levels')),
            ],
        ),
        migrations.CreateModel(
            name='False_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('learners_answer', models.CharField(max_length=255)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('Learners', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CapyStarAPI.learners')),
                ('Lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CapyStarAPI.lessons')),
                ('Question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CapyStarAPI.questionbank')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course', to='CapyStarAPI.levels'),
        ),
        migrations.AddField(
            model_name='course',
            name='Topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course', to='CapyStarAPI.topic'),
        ),
    ]
