# Generated by Django 4.2 on 2025-09-26 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapyStarAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='matching_pair',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='question_type',
            field=models.CharField(choices=[('vocabulary', 'Vocabulary'), ('reading', 'Reading'), ('grammar', 'Grammar'), ('listening', 'Listening'), ('matching', 'Matching')], max_length=50),
        ),
    ]
